export const courses = [
  'Bachelor of Science in Information and Technology',
  'Bachelor in Computer Science',
  'Bachelor of Science in Tourism',
  'Bachelor of Science in Hotel and Restaurant Management',
  'Bachelor of Science in Nursing',
]

export const users = [
  {
    id: 1,
    firstname: 'John',
    middlename: 'Michael',
    lastname: 'Doe',
    age: 21,
    birthdate: '2004-01-15',
    address: '123 Maple Street, Springfield',
    course: 'Bachelor of Science in Information and Technology',
  },
  {
    id: 2,
    firstname: 'Anna',
    middlename: 'Grace',
    lastname: 'Santos',
    age: 22,
    birthdate: '2003-05-30',
    address: '456 Elm Avenue, Quezon City',
    course: 'Bachelor in Computer Science',
  },
  {
    id: 3,
    firstname: 'Carlos',
    middlename: 'Reyes',
    lastname: 'Gomez',
    age: 20,
    birthdate: '2005-03-12',
    address: '789 Pine Road, Cebu City',
    course: 'Bachelor of Science in Tourism',
  },
  {
    id: 4,
    firstname: 'Liza',
    middlename: 'Marie',
    lastname: 'Tan',
    age: 23,
    birthdate: '2002-09-08',
    address: '321 Oak Drive, Davao City',
    course: 'Bachelor of Science in Hotel and Restaurant Management',
  },
  {
    id: 5,
    firstname: 'David',
    middlename: 'Enrique',
    lastname: 'Cruz',
    age: 24,
    birthdate: '2001-12-22',
    address: '654 Birch Lane, Baguio City',
    course: 'Bachelor of Science in Nursing',
  },
  {
    id: 6,
    firstname: 'Samantha',
    middlename: 'Joy',
    lastname: 'Lim',
    age: 21,
    birthdate: '2004-04-10',
    address: '112 Coconut St, Pasig City',
    course: 'Bachelor of Science in Information and Technology',
  },
  {
    id: 7,
    firstname: 'Miguel',
    middlename: 'Antonio',
    lastname: 'Dela Cruz',
    age: 19,
    birthdate: '2006-07-19',
    address: '245 Mango St, Makati City',
    course: 'Bachelor in Computer Science',
  },
  {
    id: 8,
    firstname: 'Erika',
    middlename: 'Rose',
    lastname: 'Mendoza',
    age: 22,
    birthdate: '2003-11-01',
    address: '77 Pearl Ave, Taguig City',
    course: 'Bachelor of Science in Tourism',
  },
  {
    id: 9,
    firstname: 'Joshua',
    middlename: 'Lee',
    lastname: 'Chua',
    age: 20,
    birthdate: '2005-06-03',
    address: '908 Tulip St, Marikina City',
    course: 'Bachelor of Science in Hotel and Restaurant Management',
  },
  {
    id: 10,
    firstname: 'Patricia',
    middlename: 'Mae',
    lastname: 'Villanueva',
    age: 23,
    birthdate: '2002-10-21',
    address: '201 Acacia Rd, Antipolo',
    course: 'Bachelor of Science in Nursing',
  },
  {
    id: 11,
    firstname: 'Leo',
    middlename: 'Andres',
    lastname: 'Torres',
    age: 22,
    birthdate: '2003-08-14',
    address: '134 Palm St, Las Piñas',
    course: 'Bachelor of Science in Information and Technology',
  },
  {
    id: 12,
    firstname: 'Clarisse',
    middlename: 'Anne',
    lastname: 'Bautista',
    age: 20,
    birthdate: '2005-09-17',
    address: '998 Mahogany Ave, Manila',
    course: 'Bachelor in Computer Science',
  },
  {
    id: 13,
    firstname: 'Nathan',
    middlename: 'Kyle',
    lastname: 'Garcia',
    age: 21,
    birthdate: '2004-05-05',
    address: '331 Baywalk, Cavite City',
    course: 'Bachelor of Science in Tourism',
  },
  {
    id: 14,
    firstname: 'Janelle',
    middlename: 'Faith',
    lastname: 'Del Rosario',
    age: 24,
    birthdate: '2001-02-28',
    address: '455 Orchid Lane, Batangas City',
    course: 'Bachelor of Science in Hotel and Restaurant Management',
  },
  {
    id: 15,
    firstname: 'Kevin',
    middlename: 'Luis',
    lastname: 'Morales',
    age: 23,
    birthdate: '2002-03-03',
    address: '621 Pineapple St, Iloilo City',
    course: 'Bachelor of Science in Nursing',
  },
  {
    id: 16,
    firstname: 'Bianca',
    middlename: 'Elaine',
    lastname: 'Reyes',
    age: 21,
    birthdate: '2004-12-11',
    address: '818 Banana Dr, Cagayan de Oro',
    course: 'Bachelor of Science in Information and Technology',
  },
  {
    id: 17,
    firstname: 'Andre',
    middlename: 'Felix',
    lastname: 'Navarro',
    age: 22,
    birthdate: '2003-07-25',
    address: '601 Olive Blvd, San Fernando',
    course: 'Bachelor in Computer Science',
  },
  {
    id: 18,
    firstname: 'Tina',
    middlename: 'Alexa',
    lastname: 'Perez',
    age: 20,
    birthdate: '2005-01-02',
    address: '742 Lavender St, General Santos',
    course: 'Bachelor of Science in Tourism',
  },
  {
    id: 19,
    firstname: 'Marcus',
    middlename: 'Vincent',
    lastname: 'Aquino',
    age: 19,
    birthdate: '2006-09-15',
    address: '372 Cherry Ave, Zamboanga',
    course: 'Bachelor of Science in Hotel and Restaurant Management',
  },
  {
    id: 20,
    firstname: 'Fiona',
    middlename: 'Claire',
    lastname: 'Lopez',
    age: 22,
    birthdate: '2003-03-20',
    address: '100 Ocean View, Puerto Princesa',
    course: 'Bachelor of Science in Nursing',
  },
]
